<fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
    <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Additional Information') ?></span></legend>
    <p>
    <div class="field giturl required">
        <label for="giturl" class="label"><span><?php /* @escapeNotVerified */
                echo __('Git URL') ?></span></label>
        <div class="control">
            <input type="text" name="git_url" id="git_url" title="<?php /* @escapeNotVerified */ echo __('Git URL') ?>" class="input-text" data-validate="{'required':true,'maxlength':200, 'validate-url':true}">
        </div>
    </div>
    </p>
</fieldset>