<?php

/* get customersession using helper */
$helper = $this->helper('Bestresponsemedia\Customers\Helper\Data');

  ?>
</fieldset>
<fieldset class="fieldset info">
    <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Additional Information') ?></span></legend><br>
    <div class="field git_url required">
        <label for="git_url" class="label"><span><?php /* @escapeNotVerified */ echo __('Git URL') ?></span></label>
        <div class="control">
            <input type="text" name="git_url" id="git_url" title="<?php /* @escapeNotVerified */ echo __('Git URL') ?>" class="input-text" value="<?php echo $helper->getCustomerSession();?>" data-validate="{'required':true,'maxlength':200, 'validate-url':true}">
        </div>
    </div>
</fieldset>